// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzpQhcgxiClFBoHLlpQdi38VS6DuBqhYk',
    appId: '1:217323127357:web:3acdca3848ca8fede6a054',
    messagingSenderId: '217323127357',
    projectId: 'crudvlad',
    authDomain: 'crudvlad.firebaseapp.com',
    storageBucket: 'crudvlad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo8g0FWcF6xAtgGZi0tKiLRcmwJ7KzkOc',
    appId: '1:217323127357:android:2ea973865da667a7e6a054',
    messagingSenderId: '217323127357',
    projectId: 'crudvlad',
    storageBucket: 'crudvlad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIUNOFprmpWm31pBaHOzawbBu2zzy_vM0',
    appId: '1:217323127357:ios:bc27f045a237363fe6a054',
    messagingSenderId: '217323127357',
    projectId: 'crudvlad',
    storageBucket: 'crudvlad.appspot.com',
    iosBundleId: 'com.example.crudvladflutter',
  );

}